#!/usr/bin/env python3
"""gitignore_gen - comprehensive .gitignore generator with 25+ templates and merge support."""

import argparse, sys, os

TEMPLATES = {
    "python": """__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
dist/
*.egg-info/
*.egg
.eggs/
*.whl
.venv/
venv/
env/
.env
.pytest_cache/
.mypy_cache/
.ruff_cache/
htmlcov/
.coverage
.tox/
.nox/
*.pyo
pip-log.txt""",

    "node": """node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm
.yarn/cache
.pnp.*
dist/
build/
.next/
out/
.nuxt/
.cache/
*.tsbuildinfo
.env
.env.local
.env.*.local
coverage/""",

    "rust": """target/
Cargo.lock
**/*.rs.bk
*.pdb""",

    "go": """bin/
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
vendor/
go.sum""",

    "java": """*.class
*.jar
*.war
*.ear
*.logs
target/
.gradle/
build/
.idea/
*.iml
out/
.settings/
.classpath
.project""",

    "c": """*.o
*.so
*.dylib
*.a
*.lib
*.exe
*.out
*.d
build/
cmake-build-*/
CMakeFiles/
CMakeCache.txt
Makefile
*.dSYM/""",

    "swift": """.build/
Packages/
xcuserdata/
*.xcscmblueprint
*.xccheckout
*.moved-aside
DerivedData/
*.hmap
*.ipa
*.dSYM.zip
*.dSYM
Carthage/build/
.swiftpm/""",

    "macos": """.DS_Store
.AppleDouble
.LSOverride
._*
.Spotlight-V100
.Trashes
.fseventsd
.TemporaryItems
.VolumeIcon.icns
.com.apple.timemachine.donotpresent""",

    "linux": """*~
.fuse_hidden*
.directory
.Trash-*
.nfs*""",

    "windows": """Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db
*.stackdump
[Dd]esktop.ini
$RECYCLE.BIN/
*.cab
*.msi
*.msix""",

    "vscode": """.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace
.history/""",

    "jetbrains": """.idea/
*.iml
*.iws
*.ipr
out/
.idea_modules/
atlassian-ide-plugin.xml
cmake-build-*/""",

    "vim": """[._]*.s[a-v][a-z]
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]sw[a-p]
Session.vim
Sessionx.vim
.netrwhist
*~
tags
[._]*.un~""",

    "docker": """*.log
.dockerignore
docker-compose*.yml
.docker/""",

    "terraform": """**/.terraform/*
*.tfstate
*.tfstate.*
crash.log
*.tfvars
override.tf
override.tf.json
*_override.tf
*_override.tf.json
.terraformrc
terraform.rc""",

    "ruby": """*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/test/tmp/
/test/version_tmp/
/tmp/
.bundle/
vendor/bundle
.byebug_history
.ruby-version
.ruby-gemset""",

    "elixir": """/_build/
/cover/
/deps/
/doc/
/.fetch
erl_crash.dump
*.ez
*.beam
/config/*.secret.exs
.elixir_ls/""",

    "latex": """*.aux
*.bbl
*.blg
*.fdb_latexmk
*.fls
*.log
*.out
*.synctex.gz
*.toc
*.lof
*.lot
*.pdf""",

    "unity": """[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db
*.pidb.meta
*.pdb.meta
*.mdb.meta
sysinfo.txt
*.apk
*.aab
*.unitypackage
crashlytics-build.properties""",

    "data": """*.csv
*.tsv
*.parquet
*.feather
*.h5
*.hdf5
*.sqlite
*.db
data/
datasets/""",

    "secrets": """.env
.env.*
*.pem
*.key
*.p12
*.pfx
*.jks
*credentials*
*secret*
.gcloud/
.aws/""",

    "logs": """*.log
logs/
*.log.*
npm-debug.log*
yarn-debug.log*""",

    "media": """*.jpg
*.jpeg
*.png
*.gif
*.bmp
*.svg
*.ico
*.mp3
*.mp4
*.avi
*.mov
*.wmv
*.flv
*.wav
*.flac
*.ogg
*.webm
*.webp""",

    "archives": """*.zip
*.tar
*.tar.gz
*.tgz
*.tar.bz2
*.rar
*.7z
*.gz
*.bz2
*.xz""",
}

def cmd_generate(args):
    templates = [t.lower() for t in args.templates]
    content = "# Generated by gitignore-gen\n"

    for t in templates:
        if t not in TEMPLATES:
            print(f"  ⚠ Unknown template: {t}", file=sys.stderr)
            continue
        content += f"\n# === {t} ===\n{TEMPLATES[t].strip()}\n"

    if args.extra:
        content += "\n# === custom ===\n"
        for e in args.extra:
            content += f"{e}\n"

    if args.output:
        mode = "a" if args.append else "w"
        with open(args.output, mode) as f:
            f.write(content)
        print(f"  {'Appended to' if args.append else 'Written'}: {args.output} ({len(content)} bytes)")
    else:
        print(content)

def cmd_list(args):
    print(f"\n  Available templates ({len(TEMPLATES)}):\n")
    categories = {
        "Languages": ["python", "node", "rust", "go", "java", "c", "swift", "ruby", "elixir"],
        "Editors": ["vscode", "jetbrains", "vim"],
        "OS": ["macos", "linux", "windows"],
        "Tools": ["docker", "terraform", "latex", "unity"],
        "Content": ["data", "secrets", "logs", "media", "archives"],
    }
    for cat, names in categories.items():
        avail = [n for n in names if n in TEMPLATES]
        print(f"  {cat}:")
        for n in avail:
            lines = len(TEMPLATES[n].strip().splitlines())
            print(f"    {n:<15} ({lines} rules)")
        print()

def cmd_check(args):
    """Check if .gitignore covers common patterns."""
    gitignore = args.file or ".gitignore"
    if not os.path.exists(gitignore):
        print(f"  {gitignore} not found")
        return

    with open(gitignore) as f:
        content = f.read()

    checks = [
        (".DS_Store", "macOS metadata"),
        ("node_modules", "Node dependencies"),
        ("__pycache__", "Python cache"),
        (".env", "Environment variables"),
        ("*.log", "Log files"),
        (".vscode", "VS Code settings"),
        (".idea", "JetBrains settings"),
        ("dist/", "Build output"),
        ("build/", "Build output"),
        ("*.pyc", "Python bytecode"),
        ("coverage/", "Test coverage"),
        ("*.pem", "Certificates/keys"),
    ]

    print(f"\n  .gitignore Coverage Check\n")
    missing = 0
    for pattern, desc in checks:
        if pattern in content:
            print(f"  ✅ {pattern:<20} {desc}")
        else:
            print(f"  ❌ {pattern:<20} {desc}")
            missing += 1
    print(f"\n  {len(checks) - missing}/{len(checks)} covered, {missing} missing\n")

def main():
    p = argparse.ArgumentParser(description=".gitignore generator")
    sp = p.add_subparsers(dest="cmd")

    g = sp.add_parser("generate", help="Generate .gitignore")
    g.add_argument("templates", nargs="+", help="Template names")
    g.add_argument("-o", "--output", help="Output file (default: stdout)")
    g.add_argument("-e", "--extra", action="append", help="Extra patterns")
    g.add_argument("-a", "--append", action="store_true")
    g.set_defaults(func=cmd_generate)

    l = sp.add_parser("list", help="List templates")
    l.set_defaults(func=cmd_list)

    c = sp.add_parser("check", help="Check .gitignore coverage")
    c.add_argument("file", nargs="?")
    c.set_defaults(func=cmd_check)

    args = p.parse_args()
    if not args.cmd:
        p.print_help()
        sys.exit(1)
    args.func(args)

if __name__ == "__main__":
    main()
